---
- hosts: minecraft
  user: minecraft
  gather_facts: False 
  sudo: no
  vars:
    # TODO: Be sure to download modpacks-server.zip next to this playbook file.
    - server_zip: modpacks-server.zip
    - root_dir: /home/minecraft/feedthebeast
  tasks:
    - name: make dir
      file: dest='{{ root_dir }}' state=directory
    - name: unzip server zip
      unarchive: src={{ server_zip }} dest={{ root_dir }}
  handlers:
    - name: start server
      shell: "cd {{root_dir}}; sh {{ root_dir }}/ServerStart.sh"
